### ISSUE TITLE
[Feature Request] Importing The Image Thumbnail Into Vault

### ISSUE THREAD

**Issue by Archie-2021** [Meikul/obsidian-thumbnails#1]
A way to get the image embedded in the note.

**Comment by Meikul** [comment]
What do you mean? Do you want to have the image downloaded into your vault?

**Comment by Archie-2021** [comment]
> What do you mean? Do you want to have the images downloaded to your vault so the thumbnails work offline?

yes please, it is just that i am depending on so many plugins right now which make me worry if they don't update anymore. that way i can use this plugin without worry for future issues

thanks

**Comment by Meikul** [comment]
Version 1.2.0 now lets you do this. Go to the settings tab and enable "Save Thumbnail Info" and then "Save Images".

**Comment by Archie-2021** [comment]
> Version 1.2.0 now lets you do this. Go to the settings tab and enable "Save Thumbnail Info" and then "Save Images".

Thank you
