### ISSUE TITLE
Deletion of additional links in "vid" codeblock

### ISSUE THREAD

**Issue by NohbdyAhtall** [Meikul/obsidian-thumbnails#2]
If I put two(or more?) YouTube links in the codeblock, it removes the others.

I perhaps would rather see it "error out" and not automatically remove stuff, because I then could not "Undo" past the embed(it would re-apply each time) and had to disable to plugin to do so.

**Comment by Meikul** [comment]
Ah, that's an unintended behavior from some new code which I was worried might have some unintended behaviors. I've added a warning for that in version 1.2.2.
