### ISSUE TITLE
Feature request: store the video

### ISSUE THREAD

**Issue by ukd1** [Meikul/obsidian-thumbnails#3]
I have been storing and downloading the videos using https://github.com/yt-dlp/yt-dlp, and manually embeddeding them. If this plugin had an option to download them, with the metadata, it could embded the thumb (or the video itself) and work even if offline, or the original video was removed.

e.g. 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/44345/186535464-c9ea5a6a-bf13-4bca-a512-984969077f97.png">

**Comment by Meikul** [comment]
That's very cool, thanks for telling me about that tool. I want to keep this plugin simple and lightweight, so I'm not going to add that sort of feature right now. There are plugins for embedding videos, and this idea might fit better with one of them. If you decide to build something like this yourself, let me know. I'd like to check it out.
