### ISSUE TITLE
Image Location: In subfolder under current folder 

### ISSUE THREAD

**Issue by StrikS** [Meikul/obsidian-thumbnails#4]
I use obsidian setting:
`Default locaton for new attachments: In subfolder under current folder`
`Subfolder name: attachments`

And plugin setting:
`Image Location: Default attachment location`

When i add thumbnail, attachment saves in `/attachments`. 
It should be saved in `path/to/current/notefolder/attachments`

Thank you for plugin and #1 realization. I like not being dependent on cloud services

**Comment by Meikul** [comment]
I'll check this out when I get a chance

**Comment by Meikul** [comment]
Trying to fix this unearthed a bunch of other problems with the way I was determining the file path, so thanks for bringing it up. Still working on it, though.

**Comment by Meikul** [comment]
I fixed this in 1.2.6. Thanks for pointing it out.

**Comment by StrikS** [comment]
Спасибо вам! ❤️
