### ISSUE TITLE
Kanban: Title should drop below thumbnail

### ISSUE THREAD

**Issue by robotcrazy8** [Meikul/obsidian-thumbnails#5]
I have tested out your plugin and it works great! I have recently started trying to transfer over all of my trello cards into the kanban plugin within obsidian and I'm noticing that your plugin doesn't conform to the 272 pixels of the standard kanban card.

I attached an image below showing the results. Ideally, it'd be great to move the right-sided Youtube title to the bottom similar to trello (bottom-left-image)

I tried editing the md vid, but I believe the plugin overrides any edits cause it doesn't let me. I tried using <br> and <p> within the md vid code block to no avail.

![Screenshot 2023-05-26 19 41 30](https://github.com/Meikul/obsidian-thumbnails/assets/70466584/ca799212-6aca-4cc2-9673-772ec5da3f3c)

**Comment by Meikul** [comment]
This should be fixed now with version 1.2.8. Let me know if it works for you.

**Comment by robotcrazy8** [comment]
Amazing! I'll check it out in a bit. Thanks for following up and following through with this. Appreciate you. Enjoy your day brother!
Heriberto

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 13, 2023 at 11:17 AM, Michael ***@***.***> wrote:   


This should be fixed now with version 1.2.8. Let me know if it works for you.
