### ISSUE TITLE
Add the option to use the YouTube Data API when OEmbed does not work

### ISSUE THREAD

**Issue by mardukbp** [Meikul/obsidian-thumbnails#6]
After using this plugin a hundred times I came across a video for which the OEmbed request fails:

https://www.youtube.com/watch?v=iG6fr81xHKA

The information about this video can be retrieved using the YouTube Data API:

https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id=iG6fr81xHKA&key=[YOUR_API_KEY]

In order to use it, it would be necessary to add a text field to the settings page to enter the API key.

Thank you so much for developing this plugin! Now I can use Obsidian to manage my YouTube playlists without missing the only good thing about playlists in the YouTube app: thumbnails.

**Comment by mardukbp** [comment]
I already implemented it. See #7.

**Comment by Meikul** [comment]
Thanks for implementing this! The fix is in 1.2.6, which I just released.
