### ISSUE TITLE
Option to add the thumbnail for a YouTube channel.

### ISSUE THREAD

**Issue by albertoloscerritos** [Meikul/obsidian-thumbnails#9]
Great plugin. I use it a lot. 
I think it would be a fantastic addition if we could create thumbnails for a YouTube channel, not a specific video.
Sometimos I want to reference a specific YouTube channel in my pages, but currently there is no option to create a thumbnail for a YouTube channel.

How it will work: I go to the home page of a YouTube channel and copy the link to the channel. Then paste in obsidian. The embed will show the name and the profile picture of said channel.

Thanks for the great work.

**Comment by Meikul** [comment]
Good idea, I like it!
I'm starting school in a few days but I'll build this sometime soon.

Glad you like the plugin 😊

**Comment by albertoloscerritos** [comment]
Sounds great. Thanks :)

**Comment by Meikul** [comment]
After looking into this idea some more, I don't know if there's a way to do it for people who don't have a YouTube API token set in the settings. The way the plugin gets info when there is no API token set only works for videos. Very few people will have the token set, so I don't want to complicate the plugin much more for a feature that basically no one will be able to use.

Cool idea, maybe if I figure out another method I'll do it someday.

**Comment by albertoloscerritos** [comment]
Hi, thanks for answering. 
I don't know if this can help, but the plugin https://github.com/nekoshita/obsidian-auto-card-link actually retrieves the image of a YouTube channel. As you can see from the following example:
![image](https://github.com/Meikul/obsidian-thumbnails/assets/16707033/5f0b0365-af9f-4b0a-885e-e1ac67edbb58)
And I didn't need to add my API in order for it to work. 
I hope this information may be useful.
